SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  image VARCHAR(255),
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_date DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  weight_grams DECIMAL(6,2) NOT NULL,
  purity VARCHAR(100) NOT NULL DEFAULT '925 Sterling Silver',
  image VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  stock_quantity INT NOT NULL DEFAULT 0,
  created_date DATE NOT NULL,
  category_id INT,
  FOREIGN KEY (category_id) REFERENCES categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- fabricate-flush

DELETE FROM `categories`;

-- fabricate-flush

ALTER TABLE `categories` AUTO_INCREMENT = 1;

-- fabricate-flush

DELETE FROM `products`;

-- fabricate-flush

ALTER TABLE `products` AUTO_INCREMENT = 1;

-- fabricate-flush


INSERT INTO `categories` (`id`, `name`, `description`, `image`, `is_active`, `created_date`) VALUES
(1, 'Anklet', 'Discover our exquisite collection of sterling silver anklets, crafted with precision and elegance for those seeking to elevate their leg jewellery with timeless style. From delicate chains to ornamental designs, our anklets are perfect for adding a subtle sparkle to any occasion, whether for everyday wear or special celebrations.', '/images/categories/anklet.jpg', 1, '2024-01-01'),
(2, 'Bangle', 'Discover our exquisite collection of silver bangles, expertly crafted to add timeless elegance to any wrist. From delicate minimalist designs to ornate statement pieces, our bangles appeal to those seeking versatile, high-quality silver jewellery that seamlessly transitions from everyday wear to special occasions.', '/images/categories/bangle.jpg', 1, '2024-01-01'),
(3, 'Bracelet', 'Discover our exquisite collection of sterling silver bracelets, featuring timeless designs from delicate chains to bold statement pieces that elevate any occasion. Perfect for those seeking sophisticated, versatile jewelry that complements both everyday style and special moments.', '/images/categories/bracelet.jpg', 1, '2024-01-01'),
(4, 'Brooch', 'Discover our exquisite collection of silver brooches, timeless pieces that add sophistication and elegance to any ensemble. Crafted with meticulous attention to detail, our brooches appeal to discerning jewelry enthusiasts and fashion-forward individuals seeking to elevate their style with versatile, statement-making accessories.', '/images/categories/brooch.jpg', 1, '2024-01-01'),
(5, 'Chain', 'Discover our exquisite collection of sterling silver chains, crafted to elevate any look with timeless elegance and versatility. From delicate, minimalist designs to bold statement pieces, our chains appeal to jewelry enthusiasts seeking quality craftsmanship and the perfect foundation for layering or wearing solo.', '/images/categories/chain.jpg', 1, '2024-01-01'),
(6, 'Cufflink', 'Elevate your formal attire with our exquisite collection of silver cufflinks, expertly crafted to add sophistication and polish to any gentleman''s wardrobe. From classic designs to contemporary styles, our cufflinks appeal to discerning professionals and those seeking timeless accessories that make a refined statement.', '/images/categories/cufflink.jpg', 1, '2024-01-01'),
(7, 'Earring', 'Discover our exquisite collection of silver earrings, crafted to elevate any style from casual to sophisticated. Each piece combines timeless elegance with contemporary design, perfect for those who appreciate quality craftsmanship and versatile accessories that complement every occasion.', '/images/categories/earring.jpg', 1, '2024-01-01'),
(8, 'Hair Pin', 'Elevate your everyday style with our exquisite collection of silver hair pins, crafted to add a touch of sophisticated elegance to any hairstyle. Perfect for both minimalist and ornate tastes, these versatile accessories appeal to anyone seeking timeless beauty and refined craftsmanship in their personal grooming.', '/images/categories/hair-pin.jpg', 1, '2024-01-01'),
(9, 'Necklace', 'Discover our exquisite collection of sterling silver necklaces, featuring timeless designs from delicate chains to statement pieces that complement any occasion. Perfect for those who appreciate refined elegance, each necklace combines craftsmanship with versatility, making it an essential accessory for everyday wear or special moments.', '/images/categories/necklace.jpg', 1, '2024-01-01'),
(10, 'Nose Pin', 'Discover our exquisite collection of silver nose pins, featuring delicate designs from traditional studs to modern artistic pieces crafted from premium sterling silver. Perfect for anyone seeking elegant, versatile adornments that add a touch of sophistication to any occasion.', '/images/categories/nose-pin.jpg', 1, '2024-01-01'),
(11, 'Pendant', 'Elegant silver pendants designed to complement any style, from delicate minimalist pieces to bold statement designs. Perfect for those seeking timeless jewelry that adds sophistication to everyday wear or special occasions.', '/images/categories/pendant.jpg', 1, '2024-01-01'),
(12, 'Ring', 'Discover our exquisite collection of sterling silver rings, expertly crafted to complement any occasion—from timeless classics to contemporary designs. Perfect for those seeking elegant, versatile pieces that blend sophistication with quality craftsmanship.', '/images/categories/ring.jpg', 1, '2024-01-01'),
(13, 'Toe Ring', 'Discover our exquisite collection of sterling silver toe rings, designed to add a delicate touch of elegance to your feet. Perfect for beach lovers, bohemian style enthusiasts, and anyone seeking to express their individuality with understated, timeless jewellery.', '/images/categories/toe-ring.jpg', 1, '2024-01-01');


-- fabricate-flush


INSERT INTO `products` (`id`, `sku`, `name`, `category`, `description`, `price`, `weight_grams`, `purity`, `image`, `is_active`, `stock_quantity`, `created_date`, `category_id`) VALUES
(1, 'SLV-BRC-001', 'Silver Cuff Bracelet', 'Bracelet', 'Elevate your style with our exquisite 925 Sterling Silver Cuff Bracelet, a timeless piece crafted with meticulous attention to detail and superior silverwork that reflects authentic Indian jewellery tradition. This versatile cuff design seamlessly transitions from casual everyday wear to festive celebrations and formal occasions, making it a must-have addition to your jewellery collection. Each bracelet showcases the lustrous beauty and durability of premium sterling silver, ensuring a piece you''ll treasure for generations to come.', 3133.9, 35, '925 Sterling Silver', '/images/products/silver-bracelet-cuff-001.jpg', 1, 83, '2024-01-04', 3),
(2, 'SLV-PND-008', 'Silver Floral Pendant', 'Pendant', 'Introducing our exquisite Silver Floral Pendant, meticulously crafted from premium 925 Sterling Silver that combines timeless elegance with contemporary design. This delicate floral-inspired piece features intricate detailing and superior craftsmanship, making it the perfect accessory for festive celebrations, weddings, daily wear, and traditional occasions. Each pendant showcases the finest quality silver work, reflecting the rich heritage of Indian jewellery artistry while offering a versatile piece that complements both ethnic and modern wardrobes.', 4425.78, 5.3, '925 Sterling Silver', '/images/products/silver-pendant-floral-008.jpg', 1, 50, '2024-01-08', 11),
(3, 'SLV-BRH-005', 'Silver Filigree Brooch', 'Brooch', 'Elevate your traditional and contemporary style with our exquisite Silver Filigree Brooch, meticulously crafted from premium 925 Sterling Silver. This stunning piece showcases intricate filigree detailing that reflects centuries of fine Indian jewellery craftsmanship, making it the perfect accessory for weddings, festivals, and everyday elegance. Whether you''re adorning a saree, kurti, or formal attire, this versatile brooch is a timeless investment that adds a touch of sophistication and cultural grace to any occasion.', 1160.59, 8.57, '925 Sterling Silver', '/images/products/silver-brooch-filigree-005.jpg', 1, 39, '2024-01-09', 4),
(4, 'SLV-BRC-004', 'Silver Tennis Bracelet', 'Bracelet', 'Introducing our exquisite Silver Tennis Bracelet, meticulously crafted from premium 999 Fine Silver that embodies timeless elegance and superior quality. This stunning piece features the classic tennis style with seamlessly aligned stones, making it the perfect accessory for both festive celebrations and everyday sophistication—ideal for weddings, engagements, and special occasions that call for refined grace. Each bracelet is a masterpiece of fine craftsmanship, designed to complement traditional attire and contemporary wear alike, making it a treasured addition to any discerning Indian jewellery collection.', 7448.81, 16.2, '999 Fine Silver', '/images/products/silver-bracelet-tennis-004.jpg', 1, 23, '2024-01-11', 3),
(5, 'SLV-ANK-003', 'Silver Beaded Anklet', 'Anklet', 'Elevate your ethnic style with our exquisite Silver Beaded Anklet, meticulously crafted from 999 Fine Silver that radiates timeless elegance and authenticity. Each delicate bead is expertly strung to create a stunning piece perfect for festivals, weddings, traditional celebrations, and everyday wear, seamlessly complementing both contemporary and traditional ensembles. This heirloom-quality anklet is a testament to fine artisanal craftsmanship, making it an ideal choice for those who appreciate pure silver jewellery with uncompromising quality and grace.', 11783.48, 10.01, '999 Fine Silver', '/images/products/silver-anklet-beaded-003.jpg', 0, 0, '2024-01-13', 1),
(6, 'SLV-BNG-006', 'Silver Plain Polished Bangle', 'Bangle', 'Elevate your everyday elegance with our exquisite Silver Plain Polished Bangle, meticulously crafted from premium 999 Fine Silver to ensure unparalleled purity and lasting brilliance. The sleek, minimalist design features a smooth, mirror-like polished finish that catches light beautifully, making it the perfect accessory for both casual gatherings and festive occasions like weddings, festivals, and celebrations. Versatile and timeless, this bangle seamlessly complements traditional Indian attire as well as modern wardrobe choices, making it an essential addition to every woman''s jewellery collection.', 18731.97, 16.81, '999 Fine Silver', '/images/products/silver-bangle-plain-polished-006.jpg', 1, 54, '2024-01-14', 2),
(7, 'SLV-BRC-009', 'Silver Chain Link Bracelet', 'Bracelet', 'Elevate your everyday elegance with our exquisite Silver Chain Link Bracelet, meticulously crafted from premium 925 Sterling Silver that guarantees lasting brilliance and durability. This versatile piece seamlessly transitions from casual gatherings to formal occasions, making it the perfect addition to any jewellery collection for the modern Indian woman who appreciates authentic craftsmanship. Adorned with interlocking chain links that showcase traditional silversmith artistry, this bracelet embodies timeless sophistication and serves as a stunning statement accessory for weddings, festivals, and everyday wear.', 24729.9, 34.74, '925 Sterling Silver', '/images/products/silver-bracelet-chain-link-009.jpg', 1, 77, '2024-01-15', 3),
(8, 'SLV-NCK-006', 'Silver Statement Collar Necklace', 'Necklace', 'Elevate your elegance with our exquisite Silver Statement Collar Necklace, meticulously crafted from premium 925 Sterling Silver by skilled artisans who blend traditional Indian craftsmanship with contemporary design. This stunning statement piece is the perfect choice for weddings, festivals, and special celebrations, commanding attention with its bold, sophisticated presence that complements both ethnic and modern ensembles. Designed for the discerning Indian woman who appreciates timeless beauty and superior quality, this collar necklace is an investment in luxury that will be cherished for generations to come.', 13754.63, 54.38, '925 Sterling Silver', '/images/products/silver-necklace-statement-collar-006.jpg', 1, 35, '2024-01-19', 9),
(9, 'SLV-NCK-007', 'Silver Lariat Necklace', 'Necklace', 'Elevate your collection with our exquisite Silver Lariat Necklace, meticulously crafted from 925 sterling silver that gleams with timeless elegance and superior quality. This sophisticated lariat style necklace seamlessly transitions from casual gatherings to formal occasions, making it the perfect companion for both everyday wear and special celebrations. Designed with impeccable craftsmanship, this versatile piece embodies the grace of traditional Indian aesthetics while offering contemporary appeal, making it an essential investment for the discerning jewellery connoisseur.', 4393.06, 40.79, '925 Sterling Silver', '/images/products/silver-necklace-lariat-007.jpg', 1, 14, '2024-02-02', 9),
(10, 'SLV-CFL-002', 'Silver Square Cufflink', 'Cufflink', 'Elevate your formal style with our exquisite Silver Square Cufflinks, meticulously crafted from premium 925 Sterling Silver that showcases timeless elegance and superior quality. Perfect for weddings, corporate events, and special occasions, these sophisticated square-design cufflinks add a touch of refined luxury to any formal ensemble. Each piece reflects the finest traditions of Indian silver craftsmanship, blending contemporary design with authentic quality that complements both traditional and modern formal wear.', 5273.48, 12.19, '925 Sterling Silver', '/images/products/silver-cufflink-square-002.jpg', 1, 32, '2024-02-03', 6),
(11, 'SLV-BRC-002', 'Silver Chain Link Bracelet', 'Bracelet', 'Elevate your everyday elegance with our exquisite Silver Chain Link Bracelet, meticulously crafted from premium 925 Sterling Silver that gleams with timeless sophistication. This intricately designed chain link bracelet seamlessly transitions from casual wear to formal occasions, making it an indispensable addition to your jewellery collection for both traditional and contemporary styling. Each piece is a testament to masterful craftsmanship, combining lustrous quality silver with impeccable design that celebrates the rich heritage of Indian jewellery traditions.', 5232.8, 23.28, '925 Sterling Silver', '/images/products/silver-bracelet-chain-link-002.jpg', 1, 32, '2024-02-08', 3),
(12, 'SLV-PND-003', 'Silver Heart Pendant', 'Pendant', 'Radiant Silver Heart Pendant exquisitely crafted from premium 925 Sterling Silver, designed to capture hearts with its timeless elegance and superior shine. This beautifully finished pendant is the perfect embodiment of love and affection, making it an ideal choice for gifting on anniversaries, engagements, or as a cherished symbol of cherished relationships. Celebrate your special moments with a piece of jewellery that combines traditional craftsmanship with contemporary design, ensuring lasting beauty and value for every occasion in life.', 11465.1, 11.54, '925 Sterling Silver', '/images/products/silver-pendant-heart-003.jpg', 1, 74, '2024-02-09', 11),
(13, 'SLV-BNG-002', 'Silver Oxidized Bangle', 'Bangle', 'Experience timeless elegance with our Silver Oxidized Bangle, meticulously crafted from premium 925 Sterling Silver that exudes authentic beauty and durability. This stunning oxidized design showcases exquisite artisanal craftsmanship, perfect for elevating your look at festive occasions, weddings, and everyday celebrations with a touch of traditional Indian sophistication. The rich, darkened silver finish creates an elegant contrast that complements both ethnic and contemporary outfits, making it an essential addition to every jewellery lover''s collection.', 16057.2, 20.37, '925 Sterling Silver', '/images/products/silver-bangle-oxidized-002.jpg', 1, 57, '2024-02-10', 2),
(14, 'SLV-NCK-010', 'Silver Princess Length Necklace', 'Necklace', 'Exquisite Silver Princess Length Necklace, meticulously crafted from 999 Fine Silver to showcase timeless elegance and premium quality. This sophisticated piece is perfect for weddings, festivals, and special celebrations, adding a luminous charm to your traditional and contemporary ensembles alike. Each necklace is a testament to fine artisanal craftsmanship, designed to be a treasured heirloom that complements the grace and beauty of every Indian woman.', 42997.41, 54.54, '999 Fine Silver', '/images/products/silver-necklace-princess-length-010.jpg', 1, 84, '2024-02-14', 9),
(15, 'SLV-NCK-004', 'Silver Layered Necklace', 'Necklace', 'Introducing our exquisite Silver Layered Necklace, meticulously crafted from premium 925 Sterling Silver with impeccable artistry that celebrates timeless elegance. This sophisticated layered design effortlessly transitions from casual everyday wear to special occasions, making it a versatile addition to any jewellery collection. Perfect for the modern Indian woman who appreciates fine craftsmanship and authentic silver jewellery that embodies grace and cultural sophistication.', 47175.35, 35.52, '925 Sterling Silver', '/images/products/silver-necklace-layered-004.jpg', 1, 10, '2024-02-15', 9),
(16, 'SLV-CHN-007', 'Silver Cable Chain', 'Chain', 'Elevate your everyday style with our exquisite Silver Cable Chain, expertly crafted from premium 925 sterling silver for timeless elegance and durability. The interlocking cable design showcases impeccable artisanal craftsmanship, perfect for layering, gifting, or wearing solo at weddings, festivals, and special celebrations. Radiant and versatile, this pure silver chain is an essential addition to every jewellery collection, combining traditional sophistication with contemporary appeal.', 26645.9, 19.52, '925 Sterling Silver', '/images/products/silver-chain-cable-007.jpg', 0, 0, '2024-03-01', 5),
(17, 'SLV-NCK-009', 'Silver Choker Necklace', 'Necklace', 'Elevate your style with our exquisite 925 Sterling Silver Choker Necklace, meticulously crafted to perfection for a timeless, elegant look that complements both traditional and contemporary wardrobes. This premium sterling silver piece features impeccable craftsmanship and lustrous finish, making it an ideal choice for weddings, festive celebrations, casual gatherings, and everyday elegance. Designed for discerning Indian jewellery enthusiasts, this versatile choker is a must-have accessory that adds a touch of sophistication to any occasion.', 11860.08, 47.51, '925 Sterling Silver', '/images/products/silver-necklace-choker-009.jpg', 1, 50, '2024-03-02', 9),
(18, 'SLV-EAR-004', 'Silver Chandelier Earring', 'Earring', 'Experience timeless elegance with our exquisite Silver Chandelier Earrings, meticulously crafted from premium 925 sterling silver to ensure lustrous brilliance and lasting durability. These stunning chandelier-style earrings are versatile enough for everyday wear while making a sophisticated statement at weddings, festivals, and special celebrations. Perfect for those who appreciate authentic Indian jewellery that blends traditional artistry with contemporary design, these earrings showcase superior craftsmanship that adds an enchanting shimmer to any ensemble.', 1730.43, 8.07, '925 Sterling Silver', '/images/products/silver-earring-chandelier-004.jpg', 1, 14, '2024-03-06', 7),
(19, 'SLV-EAR-001', 'Silver Stud Earring', 'Earring', 'Experience timeless elegance with our exquisite Silver Stud Earrings, meticulously crafted from premium 925 Sterling Silver that showcases brilliant lustre and durability. Perfect for both everyday wear and special occasions, these versatile studs complement any ensemble while adding a touch of sophisticated charm to your look. Handcrafted with precision and passion, each pair reflects the finest traditions of Indian jewellery artistry, making them an essential addition to your precious collection.', 27753.47, 6.17, '925 Sterling Silver', '/images/products/silver-earring-stud-001.jpg', 0, 0, '2024-03-09', 7),
(20, 'SLV-CFL-001', 'Silver Classic Round Cufflink', 'Cufflink', 'Exquisitely crafted from premium 950 silver, the Silver Classic Round Cufflink epitomizes timeless elegance and refined sophistication for the modern gentleman. Perfect for formal occasions, business meetings, and festive celebrations, these beautifully designed round cufflinks add a distinguished touch to your traditional and contemporary attire. Each piece is meticulously handcrafted to showcase the lustrous beauty of pure silver, making it an ideal accessory for those who appreciate fine Indian jewellery craftsmanship and impeccable quality.', 9508.85, 14.44, '950 Silver', '/images/products/silver-cufflink-classic-round-001.jpg', 0, 0, '2024-03-17', 6),
(21, 'SLV-CFL-006', 'Silver Bullet Back Cufflink', 'Cufflink', 'Elevate your formal attire with our exquisite Silver Bullet Back Cufflink, meticulously crafted from premium 925 Sterling Silver that showcases impeccable artisanal workmanship and timeless elegance. These sophisticated cufflinks are the perfect accessory for weddings, business meetings, and festive celebrations, adding a refined touch to both traditional and contemporary ensembles. Each piece reflects our commitment to superior craftsmanship and authentic quality, making it an ideal investment for the discerning Indian gentleman who values heritage and style.', 2600.74, 19.8, '925 Sterling Silver', '/images/products/silver-cufflink-bullet-back-006.jpg', 1, 26, '2024-03-17', 6),
(22, 'SLV-BRC-007', 'Silver Hinged Bracelet', 'Bracelet', 'Our exquisite 925 Sterling Silver Hinged Bracelet is a masterpiece of fine craftsmanship, designed with a sophisticated hinged mechanism that combines elegance with comfort for everyday wear and special occasions alike. The premium sterling silver construction ensures brilliance and durability, making it an ideal choice for those who appreciate authentic, high-quality jewellery that complements both traditional and contemporary styles. Perfect for gifting or personal collection, this versatile bracelet adds a touch of timeless charm to weddings, festivals, and everyday moments, resonating with the refined taste of discerning Indian jewellery enthusiasts.', 18284.31, 30.39, '925 Sterling Silver', '/images/products/silver-bracelet-hinged-007.jpg', 1, 76, '2024-03-24', 3),
(23, 'SLV-BNG-007', 'Silver Twisted Bangle', 'Bangle', 'Introducing our exquisite Silver Twisted Bangle, meticulously crafted from premium 950 silver that showcases exceptional purity and timeless elegance. The beautifully twisted design reflects traditional Indian craftsmanship blended with contemporary artistry, making it a versatile accessory perfect for both everyday wear and special occasions like festivals, weddings, and celebrations. Elevate your ethnic and modern wardrobe with this stunning bangle that effortlessly complements both traditional sarees and contemporary outfits, making it an essential addition to every Indian woman''s jewellery collection.', 1573.05, 39.68, '950 Silver', '/images/products/silver-bangle-twisted-007.jpg', 1, 56, '2024-04-07', 2),
(24, 'SLV-TOE-003', 'Silver Flower Toe Ring', 'Toe Ring', 'Introducing our exquisite Silver Flower Toe Ring, meticulously crafted from premium 925 sterling silver to bring timeless elegance to your every step. This beautifully designed piece features intricate floral patterns that capture the essence of traditional Indian craftsmanship, making it the perfect accessory for festivals, weddings, and everyday adornment. Celebrate your personal style with this versatile toe ring that seamlessly blends contemporary aesthetics with classic Indian jewellery traditions.', 956.89, 4.79, '925 Sterling Silver', '/images/products/silver-toe-ring-flower-003.jpg', 1, 43, '2024-04-18', 13),
(25, 'SLV-BRC-003', 'Silver Charm Bracelet', 'Bracelet', 'Elevate your accessory collection with our exquisite Silver Charm Bracelet, meticulously crafted from 999 Fine Silver to ensure superior quality and timeless elegance. This stunning charm bracelet is versatile enough for everyday wear yet sophisticated enough to grace your wrist at weddings, festivals, and special occasions. Perfect for those who appreciate authentic silver craftsmanship, this piece seamlessly blends traditional Indian aesthetic with contemporary design, making it an ideal investment for jewellery enthusiasts seeking both beauty and purity.', 9478.93, 13.87, '999 Fine Silver', '/images/products/silver-bracelet-charm-003.jpg', 0, 0, '2024-04-19', 3),
(26, 'SLV-RNG-009', 'Silver Eternity Band Ring', 'Ring', 'Introducing our exquisite Silver Eternity Band Ring, meticulously crafted from premium 950 silver that epitomizes timeless elegance and superior quality for the discerning Indian jewellery lover. This stunning eternity band features impeccable craftsmanship with a continuous design that symbolizes eternal love and commitment, making it the perfect choice for anniversaries, engagements, weddings, or as a cherished everyday accessory. Adorn your fingers with this sophisticated piece that seamlessly blends traditional Indian jewellery aesthetics with contemporary minimalist design, embodying both grace and enduring beauty.', 16102.94, 12.21, '950 Silver', '/images/products/silver-ring-eternity-band-009.jpg', 1, 69, '2024-05-10', 12),
(27, 'SLV-ANK-005', 'Silver Layered Anklet', 'Anklet', 'Elegant and versatile, our Silver Layered Anklet is meticulously crafted from premium 925 Sterling Silver, showcasing exquisite layered design that catches light beautifully with every step. Perfect for both traditional ceremonies and contemporary everyday wear, this timeless piece adds an understated charm and sophistication to any ensemble. Each anklet is a testament to fine craftsmanship, making it an ideal choice for those who appreciate quality Indian jewellery that seamlessly blends tradition with modern aesthetics.', 4777.66, 15.2, '925 Sterling Silver', '/images/products/silver-anklet-layered-005.jpg', 0, 0, '2024-05-20', 1),
(28, 'SLV-PND-007', 'Silver Geometric Pendant', 'Pendant', 'Elevate your style with our exquisite Silver Geometric Pendant, meticulously crafted from premium 925 Sterling Silver that guarantees timeless elegance and durability. This contemporary geometric design seamlessly blends modern aesthetics with traditional Indian craftsmanship, making it the perfect accessory for everyday wear, festive celebrations, and special occasions. Whether you''re dressing up for a wedding, festival, or casual gathering, this versatile pendant adds a touch of sophistication and artistic flair to any outfit.', 19370.93, 8.17, '925 Sterling Silver', '/images/products/silver-pendant-geometric-007.jpg', 1, 47, '2024-05-27', 11),
(29, 'SLV-BRH-001', 'Silver Floral Brooch', 'Brooch', 'Elevate your traditional and contemporary wardrobe with our exquisite Silver Floral Brooch, meticulously crafted from premium 925 Sterling Silver. This stunning floral design showcases intricate artisanal detailing and timeless elegance, making it the perfect accessory for weddings, festivals, sarees, and everyday occasions. Add a touch of sophistication and grace to any ensemble with this versatile piece that celebrates the finest in Indian jewellery craftsmanship.', 6158.9, 9.25, '925 Sterling Silver', '/images/products/silver-brooch-floral-001.jpg', 1, 30, '2024-05-30', 4),
(30, 'SLV-BRH-006', 'Silver Art Deco Brooch', 'Brooch', 'Elevate your collection with our exquisite Silver Art Deco Brooch, meticulously crafted in premium 925 Sterling Silver that embodies timeless elegance and superior quality. This stunning piece features the iconic geometric patterns and sophisticated lines characteristic of the Art Deco style, making it a perfect accessory for both formal occasions and refined everyday wear. Whether adorning a saree, suit, or dress, this versatile brooch is a treasured addition for those who appreciate fine craftsmanship and enduring beauty—a symbol of refined taste that resonates with the discerning Indian jewellery connoisseur.', 28498.6, 18.7, '925 Sterling Silver', '/images/products/silver-brooch-art-deco-006.jpg', 1, 6, '2024-05-30', 4),
(31, 'SLV-BRC-008', 'Silver Cuff Bracelet', 'Bracelet', 'Introducing our exquisite 925 Sterling Silver Cuff Bracelet, a timeless masterpiece crafted with meticulous attention to detail and unparalleled artisanal excellence. This elegant cuff bracelet showcases the lustrous brilliance of premium sterling silver, making it the perfect accessory for weddings, festivals, and everyday elegance that complements both traditional and contemporary Indian ensembles. Whether adorning your wrist for a special celebration or as a cherished everyday piece, this versatile silver cuff bracelet is a sophisticated investment in quality and style that reflects the rich heritage of Indian jewellery craftsmanship.', 3729.33, 11.67, '925 Sterling Silver', '/images/products/silver-bracelet-cuff-008.jpg', 1, 52, '2024-06-04', 3),
(32, 'SLV-PND-005', 'Silver Om Pendant', 'Pendant', 'Discover the spiritual elegance of our Silver Om Pendant, meticulously crafted in premium 925 Sterling Silver to bring timeless grace to your jewelry collection. This exquisitely designed pendant captures the sacred essence of Om, making it a perfect spiritual companion for daily wear, meditation, or special occasions while showcasing exceptional artisanal craftsmanship. Embrace the divine beauty and authenticity of authentic sterling silver that resonates with tradition, ideal for those seeking meaningful and versatile jewelry that honors their spiritual journey.', 3046.73, 5.93, '925 Sterling Silver', '/images/products/silver-pendant-om-005.jpg', 1, 40, '2024-06-06', 11),
(33, 'SLV-HRP-005', 'Silver Floral Comb Hair Pin', 'Hair Pin', 'Exquisitely crafted from premium 925 Sterling Silver, this elegant floral comb hair pin combines traditional artistry with timeless beauty, making it the perfect accessory for weddings, festivals, and special occasions. Each delicate petal is meticulously sculpted to showcase the finest silver craftsmanship, ensuring a lustrous finish that complements any hairstyle with graceful sophistication. An authentic piece of Indian jewelry that adds a touch of vintage charm and cultural elegance to your everyday look or ceremonial ensemble.', 407.16, 14.38, '925 Sterling Silver', '/images/products/silver-hair-pin-floral-comb-005.jpg', 1, 6, '2024-06-06', 8),
(34, 'SLV-NSP-001', 'Silver Stud Nose Pin', 'Nose Pin', 'Introducing our exquisite Silver Stud Nose Pin, meticulously crafted from 925 Sterling Silver with exceptional purity and brilliant shine. This elegant stud style nose pin seamlessly complements both traditional ethnic wear and contemporary fashion, making it perfect for daily wear, festivals, and special occasions. Our expert artisans have perfected every detail to deliver timeless elegance that captures the essence of Indian jewellery craftsmanship, adding a touch of sophistication to your personal style.', 1018.56, 1.41, '925 Sterling Silver', '/images/products/silver-nose-pin-stud-001.jpg', 1, 50, '2024-06-14', 10),
(35, 'SLV-PND-004', 'Silver Cross Pendant', 'Pendant', 'Introducing our exquisitely crafted Silver Cross Pendant, meticulously made from premium 925 Sterling Silver that embodies timeless elegance and spiritual significance. This beautifully designed cross pendant is perfect for daily wear or special occasions, making it an ideal choice for both personal adornment and meaningful gifting. Each piece reflects superior craftsmanship and authentic silver quality, resonating with the rich traditions of Indian jewellery lovers who appreciate fine, lasting beauty.', 27474.12, 10.33, '925 Sterling Silver', '/images/products/silver-pendant-cross-004.jpg', 1, 30, '2024-06-15', 11),
(36, 'SLV-BNG-003', 'Silver Engraved Bangle', 'Bangle', 'This exquisite 925 Sterling Silver Engraved Bangle showcases masterful craftsmanship with intricate engravings that add timeless elegance to your wrist collection. Crafted from premium grade sterling silver, this versatile bangle seamlessly transitions from everyday sophistication to festive grandeur, making it perfect for weddings, celebrations, and special occasions. With its lustrous finish and detailed artisanal detailing, this piece embodies the finest traditions of Indian silver jewellery, making it an essential addition to every jewellery enthusiast''s treasure box.', 43008.21, 46.43, '925 Sterling Silver', '/images/products/silver-bangle-engraved-003.jpg', 1, 41, '2024-06-22', 2),
(37, 'SLV-CHN-001', 'Silver Figaro Chain', 'Chain', 'Our exquisite Silver Figaro Chain is meticulously crafted from premium 925 Sterling Silver, embodying timeless elegance and superior quality that complements any wardrobe. This beautifully designed chain features the classic Figaro pattern, perfect for everyday wear or special occasions, from casual gatherings to festive celebrations and formal events. Celebrate the rich tradition of fine silver jewellery with a piece that reflects authentic craftsmanship and enduring sophistication, making it an ideal choice for those who appreciate genuine quality and refined style.', 11427.13, 48.63, '925 Sterling Silver', '/images/products/silver-chain-figaro-001.jpg', 1, 67, '2024-06-23', 5),
(38, 'SLV-BRH-003', 'Silver Animal Brooch', 'Brooch', 'Introducing our exquisite Silver Animal Brooch, meticulously crafted from premium 925 Sterling Silver that showcases impeccable artistry and timeless elegance. This stunning piece seamlessly blends traditional Indian jewellery aesthetics with contemporary design, making it the perfect accessory for weddings, festivals, casual outings, and special celebrations. Wear it with pride knowing you''re adorning yourself with authentic, high-quality sterling silver that reflects both sophistication and cultural heritage.', 420.83, 12.49, '925 Sterling Silver', '/images/products/silver-brooch-animal-003.jpg', 1, 79, '2024-06-25', 4),
(39, 'SLV-CFL-003', 'Silver Knot Cufflink', 'Cufflink', 'Introducing our exquisite Silver Knot Cufflink, meticulously crafted from premium 950 silver that epitomizes timeless elegance and superior quality. These beautifully designed cufflinks feature a sophisticated knot motif, perfect for formal occasions, weddings, and festive celebrations, elevating any traditional or contemporary ensemble with a touch of refined luxury. Each piece is a testament to masterful Indian craftsmanship, combining artistic excellence with the enduring allure of pure silver, making it an ideal choice for the discerning gentleman who values both heritage and style.', 10639.27, 9.27, '950 Silver', '/images/products/silver-cufflink-knot-003.jpg', 1, 19, '2024-06-28', 6),
(40, 'SLV-TOE-002', 'Silver Metti Toe Ring', 'Toe Ring', 'Elegantly crafted from premium 925 Sterling Silver, this exquisite Metti Toe Ring brings timeless grace to your traditional and contemporary looks. Meticulously designed with intricate detailing, this piece celebrates authentic Indian craftsmanship while maintaining lustrous brilliance and durability. Perfect for festivals, weddings, daily wear, or special occasions, this sterling silver metti is a must-have addition to every jewelry connoisseur''s collection, combining cultural heritage with refined elegance.', 646.29, 3.35, '925 Sterling Silver', '/images/products/silver-toe-ring-metti-002.jpg', 1, 28, '2024-07-08', 13),
(41, 'SLV-EAR-006', 'Silver Huggie Earring', 'Earring', 'Elegantly crafted from premium 925 Sterling Silver, these Silver Huggie Earrings showcase timeless design and exceptional craftsmanship that blends contemporary style with traditional appeal. Perfect for daily wear and special occasions alike, these versatile huggie earrings add a touch of sophistication to any ensemble, from casual gatherings to festive celebrations. Invest in jewellery that combines durability, purity, and understated elegance—a must-have staple for the modern Indian woman who values quality and refined taste.', 7690.82, 9.81, '925 Sterling Silver', '/images/products/silver-earring-huggie-006.jpg', 0, 5, '2024-07-11', 7),
(42, 'SLV-RNG-006', 'Silver Filigree Ring', 'Ring', 'Exquisite Silver Filigree Ring, meticulously crafted from premium 925 Sterling Silver, showcasing intricate traditional filigree workmanship that reflects timeless Indian artistry. This elegant ring is perfect for both everyday elegance and special occasions, seamlessly complementing traditional sarees, salwar kameez, as well as contemporary Western wear. A sophisticated accessory that celebrates the rich heritage of Indian silvercraft while adding a touch of refined beauty to your jewellery collection.', 20546.6, 7.54, '925 Sterling Silver', '/images/products/silver-ring-filigree-006.jpg', 1, 52, '2024-07-19', 12),
(43, 'SLV-ANK-001', 'Silver Chain Link Anklet', 'Anklet', 'Elevate your everyday style with our exquisite Silver Chain Link Anklet, meticulously crafted from premium 925 Sterling Silver that ensures durability and timeless elegance. This beautifully designed chain link anklet seamlessly transitions from casual daywear to festive occasions, making it a versatile addition to your jewellery collection—perfect for adorning your feet during celebrations, weddings, or intimate family gatherings. Each piece reflects superior craftsmanship and authentic silver quality, embodying the grace and tradition that Indian jewellery lovers cherish.', 2500.95, 23.95, '925 Sterling Silver', '/images/products/silver-anklet-chain-link-001.jpg', 1, 40, '2024-07-24', 1),
(44, 'SLV-CHN-004', 'Silver Curb Chain', 'Chain', 'Elevate your style with our exquisite 925 Sterling Silver Curb Chain, a masterpiece of fine craftsmanship that seamlessly blends timeless elegance with contemporary design. This premium quality chain features a robust curb link pattern, perfect for both casual everyday wear and special occasions, from festive celebrations to formal gatherings. Crafted with pure sterling silver, this versatile piece is an essential addition to any jewellery collection and makes for a meaningful gift for your loved ones.', 19345.71, 25.47, '925 Sterling Silver', '/images/products/silver-chain-curb-004.jpg', 1, 47, '2024-08-05', 5),
(45, 'SLV-BNG-005', 'Silver Stone-studded Bangle', 'Bangle', 'Elevate your everyday style with our exquisite Silver Stone-studded Bangle, meticulously crafted from premium 925 Sterling Silver. This stunning piece seamlessly blends traditional Indian artistry with contemporary elegance, featuring intricate stone embellishments that catch the light beautifully, making it perfect for weddings, festivals, and special celebrations. Whether you''re adorning your wrists for a festive gathering or adding a touch of sophistication to your daily ensemble, this versatile bangle is a timeless treasure that complements both traditional attire and modern fashion.', 37366.72, 38.2, '925 Sterling Silver', '/images/products/silver-bangle-stone-studded-005.jpg', 0, 9, '2024-08-10', 2),
(46, 'SLV-RNG-007', 'Silver Dome Ring', 'Ring', 'Elevate your style with our exquisite Silver Dome Ring, meticulously crafted from premium 925 sterling silver that showcases timeless elegance and superior durability. This beautifully designed dome-shaped ring is perfect for everyday wear, festive celebrations, weddings, and special occasions, making it an essential addition to any jewellery collection. Each piece reflects authentic craftsmanship and the finest quality silver, ensuring you wear not just jewellery, but a masterpiece that blends traditional aesthetics with contemporary design.', 3825.77, 10.01, '925 Sterling Silver', '/images/products/silver-ring-dome-007.jpg', 1, 72, '2024-08-19', 12),
(47, 'SLV-NSP-005', 'Silver Septum Ring Nose Pin', 'Nose Pin', 'Elevate your style with our exquisite Silver Septum Ring Nose Pin, meticulously crafted from premium 925 Sterling Silver that promises lasting brilliance and durability. This versatile piece seamlessly blends traditional Indian aesthetics with contemporary elegance, making it perfect for weddings, festivals, casual outings, and everyday wear. Designed for those who appreciate fine craftsmanship and authentic silver jewellery, this stunning septum ring is an essential addition to every jewellery collection.', 1582.21, 2.88, '925 Sterling Silver', '/images/products/silver-nose-pin-septum-ring-005.jpg', 1, 75, '2024-08-20', 10),
(48, 'SLV-HRP-004', 'Silver Tikka Hair Pin', 'Hair Pin', 'Elevate your traditional elegance with our exquisite Silver Tikka Hair Pin, masterfully crafted from 925 Sterling Silver to complement your festive and ceremonial looks. This intricately designed piece seamlessly blends timeless Indian artistry with premium quality, perfect for weddings, festivals, and special occasions. Secure your hair in style while adding an authentic touch of sophistication to your ensemble with this stunning handcrafted accessory.', 3284.87, 7.01, '925 Sterling Silver', '/images/products/silver-hair-pin-tikka-004.jpg', 1, 26, '2024-08-25', 8),
(49, 'SLV-CFL-005', 'Silver Gemstone Cufflink', 'Cufflink', 'Experience timeless elegance with our exquisite 925 Sterling Silver Gemstone Cufflinks, a masterpiece of fine craftsmanship that seamlessly blends luxury with sophistication. Perfect for weddings, corporate events, and festive celebrations, these stunning gemstone-adorned cufflinks add a touch of refined grace to any formal ensemble. Each piece is meticulously crafted to showcase the pristine quality of premium sterling silver, embodying the rich heritage of Indian jewellery artistry and making them an ideal choice for the discerning collector.', 11818.04, 15.65, '925 Sterling Silver', '/images/products/silver-cufflink-gemstone-005.jpg', 1, 73, '2024-08-28', 6),
(50, 'SLV-BNG-004', 'Silver Temple Bangle', 'Bangle', 'Exquisitely crafted with 925 Sterling Silver, the Silver Temple Bangle showcases authentic temple-style artistry and traditional craftsmanship that reflects timeless Indian elegance. This versatile piece seamlessly blends cultural heritage with contemporary style, making it perfect for festivals, weddings, and everyday celebrations while maintaining its lustrous appeal. Invest in pure silver jewelry that honors tradition and adds a touch of spiritual grace to your personal collection.', 2163.37, 21.66, '925 Sterling Silver', '/images/products/silver-bangle-temple-004.jpg', 1, 11, '2024-08-31', 2),
(51, 'SLV-EAR-002', 'Silver Hoop Earring', 'Earring', 'Elevate your elegance with our exquisite 925 Sterling Silver Hoop Earrings, masterfully crafted to perfection for the discerning Indian woman. These timeless hoops seamlessly complement both traditional and contemporary outfits, making them an ideal choice for everyday wear, festivals, weddings, and special occasions. Each pair showcases authentic sterling silver craftsmanship that promises enduring brilliance, durability, and the lustrous charm that defines true silver jewellery.', 5067.76, 11.18, '925 Sterling Silver', '/images/products/silver-earring-hoop-002.jpg', 1, 22, '2024-09-12', 7),
(52, 'SLV-NCK-002', 'Silver Princess Length Necklace', 'Necklace', 'Elegant and timeless, our Silver Princess Length Necklace is crafted from premium 999 fine silver, showcasing exquisite artistry and uncompromising quality that Indian jewellery connoisseurs cherish. This graceful 18-inch masterpiece is the perfect companion for both traditional festive occasions and contemporary celebrations, from weddings and festivals to everyday sophistication. Radiating a lustrous brilliance that complements every skin tone, this sterling silver treasure is an investment piece that transcends trends and becomes a cherished heirloom.', 4646.99, 28.13, '999 Fine Silver', '/images/products/silver-necklace-princess-length-002.jpg', 1, 70, '2024-09-19', 9),
(53, 'SLV-NSP-006', 'Silver Nath Nose Pin', 'Nose Pin', 'Elevate your traditional look with our exquisite Silver Nath Nose Pin, meticulously crafted from premium 925 Sterling Silver to ensure lasting brilliance and durability. This elegant nath beautifully blends timeless craftsmanship with contemporary design, making it the perfect accessory for weddings, festivals, and special occasions. Adorned with refined detailing and lustrous finish, this nose pin is an essential piece for any jewellery collection, adding a touch of sophistication and cultural grace to your everyday style.', 3980.06, 2.71, '925 Sterling Silver', '/images/products/silver-nose-pin-nath-006.jpg', 1, 52, '2024-09-22', 10),
(54, 'SLV-TOE-004', 'Silver Spiral Toe Ring', 'Toe Ring', 'Adorn your feet with this exquisite Silver Spiral Toe Ring, meticulously crafted from premium 925 sterling silver that ensures lasting brilliance and durability. The mesmerizing spiral design adds an elegant touch to your aesthetic, making it perfect for festivals, weddings, casual gatherings, or everyday wear. This timeless piece celebrates traditional Indian jewelry artistry while offering a modern, sophisticated look that complements both contemporary and ethnic outfits.', 1711.93, 3.59, '925 Sterling Silver', '/images/products/silver-toe-ring-spiral-004.jpg', 1, 41, '2024-10-02', 13),
(55, 'SLV-CHN-005', 'Silver Snake Chain', 'Chain', 'Elevate your style with our exquisite Silver Snake Chain, meticulously crafted from premium 925 Sterling Silver that ensures lasting brilliance and durability. This timeless piece features an intricate snake design that seamlessly blends traditional Indian aesthetics with contemporary elegance, making it perfect for both everyday wear and special occasions like festivals, weddings, and celebrations. Whether you''re looking for a sophisticated accessory to complement your traditional attire or a versatile statement piece for modern fashion, this handcrafted silver chain is a treasured addition to any jewellery collection.', 7117.9, 23.76, '925 Sterling Silver', '/images/products/silver-chain-snake-005.jpg', 1, 17, '2024-10-18', 5),
(56, 'SLV-TOE-001', 'Silver Adjustable Band Toe Ring', 'Toe Ring', 'Embrace timeless elegance with our exquisite Silver Adjustable Band Toe Ring, meticulously crafted from premium 999 Fine Silver that ensures lasting brilliance and durability. This versatile adjustable band design seamlessly fits any toe size, making it the perfect accessory for daily wear, festive celebrations, and traditional occasions. Whether adorning your feet for weddings, festivals, or everyday sophistication, this beautifully crafted toe ring is a testament to authentic Indian jewellery craftsmanship and a cherished addition to your personal collection.', 765.89, 4.68, '999 Fine Silver', '/images/products/silver-toe-ring-adjustable-band-001.jpg', 1, 72, '2024-11-10', 13),
(57, 'SLV-ANK-002', 'Silver Charm Anklet', 'Anklet', 'Elevate your everyday elegance with our exquisite Silver Charm Anklet, meticulously crafted from premium 925 Sterling Silver that gleams with timeless radiance. This delicately designed charm anklet effortlessly transitions from casual day-wear to festive occasions, making it a versatile essential for every Indian woman''s jewellery collection. With its impeccable craftsmanship and lustrous finish, this piece celebrates the perfect blend of traditional charm and contemporary style, ideal for adorning your ankles with grace at weddings, celebrations, or intimate gatherings.', 35126.48, 22.95, '925 Sterling Silver', '/images/products/silver-anklet-charm-002.jpg', 0, 4, '2024-11-15', 1),
(58, 'SLV-CHN-006', 'Silver Wheat Chain', 'Chain', 'Introducing our exquisite Silver Wheat Chain, meticulously crafted from premium 925 Sterling Silver with an elegant wheat design that showcases traditional artistry and timeless sophistication. This beautifully woven chain is the perfect accessory for everyday elegance or special occasions, seamlessly complementing both casual wear and festive attire at weddings, celebrations, and religious ceremonies. Each piece reflects our commitment to exceptional craftsmanship and authentic Indian jewelry traditions, making it an ideal investment for those who appreciate quality silver jewelry that blends cultural heritage with contemporary style.', 18320.55, 49.92, '925 Sterling Silver', '/images/products/silver-chain-wheat-006.jpg', 1, 74, '2024-11-15', 5),
(59, 'SLV-RNG-008', 'Silver Signet Ring', 'Ring', 'Introducing our exquisite 925 Sterling Silver Signet Ring, a timeless piece of jewellery crafted with meticulous attention to detail and superior silversmithing techniques. This elegant ring seamlessly blends traditional Indian design sensibilities with contemporary sophistication, making it the perfect accessory for both everyday wear and special occasions—from festive celebrations to formal gatherings and professional settings. Adorned with the lustre of premium sterling silver, this versatile signet ring is a worthy addition to any jewellery collection, embodying elegance, heritage, and lasting quality that transcends generations.', 40423.86, 9.66, '925 Sterling Silver', '/images/products/silver-ring-signet-008.jpg', 1, 43, '2024-11-19', 12),
(60, 'SLV-RNG-005', 'Silver Statement Ring', 'Ring', 'Make a bold impression with our exquisite Silver Statement Ring, meticulously crafted from premium 950 silver that ensures lasting brilliance and durability. This stunning piece combines timeless elegance with contemporary flair, perfect for elevating your look at weddings, festivals, celebrations, or as an everyday luxury accessory. Each ring is a masterpiece of fine craftsmanship, reflecting our commitment to authentic Indian jewellery artistry that speaks to your sophisticated taste.', 10548.84, 5.69, '950 Silver', '/images/products/silver-ring-statement-005.jpg', 1, 79, '2024-11-21', 12),
(61, 'SLV-TOE-005', 'Silver Beaded Toe Ring', 'Toe Ring', 'Elegant Silver Beaded Toe Ring - Exquisitely crafted from premium 950 silver, this delicate beaded toe ring showcases exceptional Indian craftsmanship with its intricately designed beaded pattern that catches light beautifully. Perfect for adding a touch of traditional charm to everyday wear, festive occasions, or special celebrations, this versatile piece complements both casual and formal ethnic attire. A timeless accessory that embodies the grace of authentic silver jewellery, ideal for those who appreciate the perfect blend of tradition and contemporary elegance.', 7562.74, 3.51, '950 Silver', '/images/products/silver-toe-ring-beaded-005.jpg', 1, 27, '2024-11-21', 13),
(62, 'SLV-PND-001', 'Silver Locket Pendant', 'Pendant', 'Discover the timeless elegance of our exquisite Silver Locket Pendant, meticulously crafted from 999 fine silver that gleams with authentic brilliance and unmatched purity. This heirloom-quality piece features intricate artisanal detailing that reflects the rich heritage of Indian jewellery craftsmanship, making it the perfect keepsake for cherished moments and cherished memories. Whether adorning yourself for festivals, weddings, daily wear, or special occasions, this versatile locket pendant is an investment in sophistication that transcends generations and complements any ensemble with refined grace.', 30832.59, 19.92, '999 Fine Silver', '/images/products/silver-pendant-locket-001.jpg', 1, 22, '2024-12-03', 11),
(63, 'SLV-RNG-003', 'Silver Cocktail Ring', 'Ring', 'Experience timeless elegance with our exquisite Silver Cocktail Ring, meticulously crafted from premium 925 Sterling Silver that gleams with unparalleled lustre and purity. This stunning statement piece is the perfect accessory for festive occasions, upscale dinners, and special celebrations, designed to complement both traditional and contemporary styling. Each ring is expertly crafted by skilled artisans who pour their passion into every detail, making it a treasured addition to your jewellery collection that embodies authentic Indian craftsmanship.', 43902.11, 8.92, '925 Sterling Silver', '/images/products/silver-ring-cocktail-003.jpg', 1, 66, '2024-12-04', 12),
(64, 'SLV-RNG-001', 'Silver Twisted Band Ring', 'Ring', 'Discover the elegance of our Silver Twisted Band Ring, meticulously crafted from premium 925 Sterling Silver that gleams with timeless sophistication. The intricately twisted band design showcases exceptional artisanal craftsmanship, making it a versatile piece perfect for everyday wear, festivals, and special occasions. This stunning ring seamlessly complements both traditional and contemporary outfits, reflecting the refined taste of jewelry connoisseurs who appreciate authentic, high-quality silver pieces.', 39897.65, 9.42, '925 Sterling Silver', '/images/products/silver-ring-twisted-band-001.jpg', 1, 81, '2024-12-08', 12),
(65, 'SLV-HRP-003', 'Silver Juda Pin Hair Pin', 'Hair Pin', 'Elevate your traditional look with our exquisite Silver Juda Pin, meticulously crafted from premium 999 Fine Silver by skilled artisans. This elegant hair accessory is the perfect blend of heritage and sophistication, ideal for weddings, festivals, and special occasions when you want to add a touch of authentic Indian elegance to your hairstyle. Adorned with timeless design and superior craftsmanship, this juda pin is a must-have for every woman who cherishes fine silver jewellery.', 18049.14, 9.9, '999 Fine Silver', '/images/products/silver-hair-pin-juda-pin-003.jpg', 1, 41, '2024-12-10', 8),
(66, 'SLV-RNG-002', 'Silver Solitaire Ring', 'Ring', 'Experience timeless elegance with our exquisite Silver Solitaire Ring, meticulously crafted from 999 Fine Silver that exemplifies superior purity and radiant brilliance. This stunning solitaire design, perfected through traditional Indian jewellery craftsmanship, makes it the perfect choice for engagements, weddings, festive occasions, or as an everyday statement piece that celebrates your refined taste. The pristine silver''s lustrous finish and minimalist solitaire setting ensure this ring complements both traditional and contemporary wardrobes, making it an heirloom-worthy investment for the discerning jewellery enthusiast.', 7777.59, 7.21, '999 Fine Silver', '/images/products/silver-ring-solitaire-002.jpg', 1, 14, '2024-12-21', 12),
(67, 'SLV-EAR-009', 'Silver Stud Earring', 'Earring', 'Elevate your everyday elegance with these exquisite 925 Sterling Silver Stud Earrings, meticulously crafted to perfection by skilled artisans. These timeless studs seamlessly transition from casual office wear to festive celebrations, making them an essential addition to every Indian woman''s jewellery collection. The premium purity of sterling silver ensures lasting brilliance and durability, offering you a versatile accessory that complements both traditional and contemporary styles.', 3756.64, 3.67, '925 Sterling Silver', '/images/products/silver-earring-stud-009.jpg', 1, 44, '2024-12-22', 7),
(68, 'SLV-ANK-007', 'Silver Chain Link Anklet', 'Anklet', 'Discover the timeless elegance of our Silver Chain Link Anklet, meticulously crafted from 999 Fine Silver that guarantees exceptional purity and lasting brilliance. This exquisitely designed piece features a smooth, interconnected chain link pattern that effortlessly complements both traditional and contemporary styles, making it the perfect accessory for festivals, celebrations, or everyday wear. Embrace authentic craftsmanship and the enduring beauty of premium silver with this sophisticated anklet that resonates with the rich heritage of Indian jewellery tradition.', 2207.22, 27.9, '999 Fine Silver', '/images/products/silver-anklet-chain-link-007.jpg', 1, 40, '2024-12-26', 1),
(69, 'SLV-NSP-004', 'Silver Screw Back Nose Pin', 'Nose Pin', 'Experience timeless elegance with our exquisite 999 Fine Silver Screw Back Nose Pin, meticulously crafted to perfection for the discerning Indian woman. This versatile and secure screw back design ensures comfort and stability throughout your day, whether you''re attending festive celebrations, weddings, or adding a touch of sophistication to your everyday style. Adorned with our premium pure silver craftsmanship, this nose pin is a cherished accessory that complements both traditional and contemporary looks, making it an essential piece in your jewellery collection.', 3541.15, 1.7, '999 Fine Silver', '/images/products/silver-nose-pin-screw-back-004.jpg', 1, 76, '2024-12-29', 10),
(70, 'SLV-CHN-002', 'Silver Rope Chain', 'Chain', 'Elevate your style with our exquisite Silver Rope Chain, meticulously crafted from premium 950 Silver that showcases the finest purity and lustrous finish. This beautifully woven rope design brings timeless elegance to any occasion, whether you''re dressing up for festive celebrations, traditional ceremonies, or everyday sophistication. Perfect for layering or wearing standalone, this handcrafted piece embodies the true essence of Indian silver jewellery craftsmanship and is sure to become a cherished addition to your collection.', 1513.3, 47.14, '950 Silver', '/images/products/silver-chain-rope-002.jpg', 1, 6, '2025-01-01', 5),
(71, 'SLV-NCK-008', 'Silver Bib Necklace', 'Necklace', 'Elevate your ethnic wardrobe with our exquisite 925 Sterling Silver Bib Necklace, meticulously crafted to showcase timeless elegance and unparalleled quality. This stunning statement piece features intricate detailing and a flattering silhouette that beautifully complements both traditional sarees and contemporary fusion wear, making it the perfect accessory for weddings, festive celebrations, and special occasions. Handcrafted with precision using premium 925 sterling silver, this necklace promises durability and lasting brilliance that will make you shine with grace and sophistication.', 5154.11, 36.17, '925 Sterling Silver', '/images/products/silver-necklace-bib-008.jpg', 1, 83, '2025-01-16', 9),
(72, 'SLV-RNG-010', 'Silver Minimalist Ring', 'Ring', 'Introducing our exquisite Silver Minimalist Ring, expertly crafted from premium 925 Sterling Silver that radiates timeless elegance and understated sophistication. This beautifully minimalist design seamlessly transitions from casual everyday wear to special occasions, making it an essential addition to every jewellery collection—perfect for those who appreciate refined craftsmanship and authentic silver artistry. Celebrate your unique style with this versatile piece that embodies the perfect blend of traditional silver excellence and contemporary minimalist aesthetics, cherished by discerning Indian jewellery enthusiasts.', 3293.48, 3.39, '925 Sterling Silver', '/images/products/silver-ring-minimalist-010.jpg', 1, 52, '2025-01-18', 12),
(73, 'SLV-BRC-006', 'Silver Wrap Bracelet', 'Bracelet', 'Introducing our exquisite Silver Wrap Bracelet, meticulously crafted from premium 925 Sterling Silver that radiates timeless elegance and authenticity. This versatile wrap-style bracelet beautifully complements both traditional Indian attire and contemporary western wear, making it the perfect accessory for weddings, festivals, casual outings, and everyday moments of grace. Each piece is masterfully handcrafted to perfection, showcasing fine artisanal workmanship that celebrates the rich heritage of Indian silver jewellery making.', 7585.79, 14.93, '925 Sterling Silver', '/images/products/silver-bracelet-wrap-006.jpg', 1, 13, '2025-01-19', 3),
(74, 'SLV-PND-006', 'Silver Leaf Pendant', 'Pendant', 'Elevate your everyday elegance with our exquisite Silver Leaf Pendant, meticulously crafted from premium 925 sterling silver that promises timeless brilliance and lasting durability. This beautifully designed leaf-shaped pendant captures nature''s delicate grace, making it the perfect accessory for festive celebrations, wedding ceremonies, or refined everyday wear. Each piece is a testament to our commitment to superior craftsmanship and authentic silver quality, making it an ideal choice for discerning jewelry enthusiasts who appreciate both traditional artistry and contemporary design.', 5560.42, 19.09, '925 Sterling Silver', '/images/products/silver-pendant-leaf-006.jpg', 1, 51, '2025-01-21', 11),
(75, 'SLV-BRH-002', 'Silver Vintage Brooch', 'Brooch', 'Elevate your vintage style with our exquisite Silver Vintage Brooch, meticulously crafted from premium 925 Sterling Silver that showcases timeless elegance and superior quality. This ornate brooch is the perfect accessory for weddings, festive celebrations, traditional gatherings, and everyday elegance, reflecting the rich heritage of Indian jewellery craftsmanship. Each piece is expertly designed to add a touch of sophistication to your saree, kurti, or Western attire, making it an essential heirloom treasure for the discerning jewellery connoisseur.', 540.32, 12.12, '925 Sterling Silver', '/images/products/silver-brooch-vintage-002.jpg', 1, 6, '2025-01-22', 4),
(76, 'SLV-ANK-004', 'Silver Ghungroo Anklet', 'Anklet', 'Introducing our exquisite Silver Ghungroo Anklet, a timeless piece crafted from premium 925 Sterling Silver that embodies the essence of traditional Indian artistry. Each delicate ghungroo is meticulously arranged and hand-finished to create a harmonious melody of elegance, perfect for festivals, weddings, and everyday celebrations. This authentic sterling silver creation is an ideal companion for cultural occasions, festive gatherings, or adding a touch of graceful charm to your everyday ensemble.', 22181.72, 25.47, '925 Sterling Silver', '/images/products/silver-anklet-ghungroo-004.jpg', 1, 62, '2025-01-29', 1),
(77, 'SLV-EAR-008', 'Silver Climber Earring', 'Earring', 'Elevate your everyday elegance with our exquisite Silver Climber Earring, meticulously crafted from premium 950 silver that showcases superior craftsmanship and timeless sophistication. These stunning climber earrings are the perfect choice for both intimate celebrations and formal occasions, seamlessly transitioning from traditional wear to contemporary styles favored by Indian jewelry enthusiasts. The refined design and lustrous finish of these earrings make them an indispensable addition to your jewelry collection, embodying the perfect blend of classic artistry and modern aesthetic appeal.', 5746.51, 6.12, '950 Silver', '/images/products/silver-earring-climber-008.jpg', 0, 5, '2025-02-03', 7),
(78, 'SLV-NCK-001', 'Silver Choker Necklace', 'Necklace', 'Elevate your elegance with our exquisite 925 Sterling Silver Choker Necklace, meticulously crafted to perfection for the discerning woman who values timeless sophistication. This stunning piece seamlessly transitions from festive celebrations and weddings to everyday grace, showcasing the finest quality of pure silver that promises lasting brilliance and durability. Adorned with traditional artistry and contemporary design sensibilities, this choker is the perfect complement to both traditional sarees and modern ensembles, making it an essential addition to your jewellery collection.', 24184.17, 36.08, '925 Sterling Silver', '/images/products/silver-necklace-choker-001.jpg', 1, 10, '2025-02-05', 9),
(79, 'SLV-NSP-002', 'Silver Hoop Nose Pin', 'Nose Pin', 'Elevate your everyday style with our exquisite Silver Hoop Nose Pin, meticulously crafted from premium 950 silver that ensures lasting brilliance and durability. This elegant hoop design seamlessly transitions from casual daily wear to festive celebrations, making it a versatile essential for the modern Indian woman who appreciates fine craftsmanship. The lustrous finish and intricate detailing of this timeless piece reflect our commitment to superior quality, offering you authentic silver jewellery that honors traditional aesthetics while complementing contemporary fashion sensibilities.', 1782.97, 2.3, '950 Silver', '/images/products/silver-nose-pin-hoop-002.jpg', 1, 55, '2025-02-19', 10),
(80, 'SLV-HRP-006', 'Silver Vintage Hair Pin', 'Hair Pin', 'Elevate your traditional and contemporary looks with our exquisite Silver Vintage Hair Pin, meticulously crafted from premium 950 silver that showcases timeless elegance and superior quality. This intricately designed piece blends vintage aesthetics with fine craftsmanship, making it the perfect accessory for weddings, festivals, formal gatherings, and everyday sophistication. Adorn yourself with a piece that honors the rich heritage of Indian jewellery while adding a touch of refined grace to your hairstyle.', 21834.96, 7.06, '950 Silver', '/images/products/silver-hair-pin-vintage-006.jpg', 1, 17, '2025-02-26', 8),
(81, 'SLV-NSP-003', 'Silver L-Bend Nose Pin', 'Nose Pin', 'Elevate your traditional look with our exquisite Silver L-Bend Nose Pin, crafted from premium 999 fine silver that reflects unparalleled purity and lustrous beauty. This elegantly designed L-bend style piece is perfect for weddings, festivals, and everyday wear, seamlessly blending timeless charm with contemporary aesthetics. Each pin is meticulously handcrafted to ensure exceptional quality and comfort, making it an ideal addition to any jewellery collection.', 14022.27, 2.69, '999 Fine Silver', '/images/products/silver-nose-pin-l-bend-003.jpg', 1, 9, '2025-03-14', 10),
(82, 'SLV-BNG-001', 'Silver Kada Bangle', 'Bangle', 'Elevate your ethnic look with our exquisite Silver Kada Bangle, crafted from premium 950 silver that showcases exceptional purity and timeless elegance. This traditional kada design combines authentic Indian craftsmanship with contemporary aesthetics, making it the perfect accessory for weddings, festivals, and everyday celebrations. Whether you''re dressing up for a special occasion or adding a touch of sophistication to your daily attire, this sterling silver bangle is a versatile treasure that complements every wardrobe.', 15572.56, 40.43, '950 Silver', '/images/products/silver-bangle-kada-001.jpg', 1, 83, '2025-03-23', 2),
(83, 'SLV-EAR-005', 'Silver Jhumka Earring', 'Earring', 'Elevate your ethnic style with our exquisite Silver Jhumka Earring, meticulously crafted in premium 950 silver that showcases the finest quality and durability. These traditionally designed jhumkas are perfect for weddings, festivals, and special occasions, adding an authentic touch of elegance and charm to your festive ensemble. Each pair is a testament to masterful craftsmanship, blending timeless Indian design with superior silver purity for a jewelry piece that truly stands out.', 4617.16, 11.93, '950 Silver', '/images/products/silver-earring-jhumka-005.jpg', 1, 49, '2025-03-24', 7),
(84, 'SLV-TOE-006', 'Silver Traditional Toe Ring', 'Toe Ring', 'Elevate your traditional look with this exquisite Silver Traditional Toe Ring, meticulously crafted from premium 925 Sterling Silver that ensures lasting brilliance and durability. This timeless piece beautifully combines authentic craftsmanship with sophisticated design, making it the perfect accessory for festivals, weddings, and everyday elegance. Adorned with intricate detailing, this toe ring celebrates the rich heritage of Indian jewellery while adding a touch of refined grace to your personal style.', 1669.42, 3.32, '925 Sterling Silver', '/images/products/silver-toe-ring-traditional-006.jpg', 1, 80, '2025-03-29', 13),
(85, 'SLV-NCK-003', 'Silver Opera Length Necklace', 'Necklace', 'Elevate your timeless elegance with our exquisite Silver Opera Length Necklace, meticulously crafted from premium 950 silver that exudes sophistication and luxury. This stunning piece, designed in the classic opera length style, is the perfect companion for special occasions, from festive celebrations and weddings to refined evening gatherings, making it an essential addition to every Indian jewellery collection. Our master craftsmen have poured their expertise into every detail, creating a necklace that seamlessly blends traditional Indian aesthetics with contemporary design, ensuring you shine with grace and cultural pride.', 11237.85, 45.22, '950 Silver', '/images/products/silver-necklace-opera-length-003.jpg', 1, 31, '2025-04-07', 9),
(86, 'SLV-HRP-001', 'Silver Bobby Pin Hair Pin', 'Hair Pin', 'Elevate your everyday hairstyle with our exquisite 925 Sterling Silver Bobby Pin, meticulously crafted to blend timeless elegance with contemporary style. This premium hair accessory showcases the lustrous beauty and purity of authentic sterling silver, making it perfect for everything from casual day-to-day wear to special occasions, weddings, and festive celebrations. Each piece is designed with meticulous attention to detail, reflecting the rich tradition of Indian silver craftsmanship while adding a sophisticated touch to your personal adornment collection.', 5987.07, 5.02, '925 Sterling Silver', '/images/products/silver-hair-pin-bobby-pin-001.jpg', 1, 10, '2025-04-11', 8),
(87, 'SLV-EAR-003', 'Silver Drop Earring', 'Earring', 'Introducing our exquisitely crafted Silver Drop Earring, meticulously designed to showcase the finest 950 sterling silver with timeless elegance. Perfect for both everyday wear and special occasions, these stunning drop earrings effortlessly elevate any ensemble with their graceful silhouette and superior silver craftsmanship. Celebrate your refined taste with a piece that embodies authentic Indian jewellery traditions, blending contemporary style with enduring quality that''s sure to become a cherished part of your collection.', 5049.8, 9.59, '950 Silver', '/images/products/silver-earring-drop-003.jpg', 1, 49, '2025-04-14', 7),
(88, 'SLV-CHN-008', 'Silver Franco Chain', 'Chain', 'Elevate your style with our exquisite Silver Franco Chain, meticulously crafted from premium 925 sterling silver that ensures lasting brilliance and durability. This intricately woven Franco design showcases exceptional craftsmanship, making it the perfect accessory for both everyday elegance and special occasions, from festive celebrations to formal events. Versatile and timeless, this sophisticated chain complements traditional as well as contemporary Indian aesthetics, making it an essential addition to every jewellery collection.', 2664.46, 16.97, '925 Sterling Silver', '/images/products/silver-chain-franco-008.jpg', 1, 27, '2025-04-22', 5),
(89, 'SLV-EAR-007', 'Silver Threader Earring', 'Earring', 'Elegantly designed Silver Threader Earrings crafted from premium 925 Sterling Silver, these versatile earrings feature delicate threader styling that gracefully adorns the earlobe with timeless sophistication. Perfect for both everyday elegance and special occasions, these earrings seamlessly complement traditional attire as well as contemporary fashion, making them an essential addition to every jewellery collection. Handcrafted with meticulous attention to detail, these Sterling Silver threaders showcase exceptional craftsmanship and lustre that reflects the authentic beauty of fine Indian jewellery.', 18627.75, 4.56, '925 Sterling Silver', '/images/products/silver-earring-threader-007.jpg', 0, 0, '2025-04-23', 7),
(90, 'SLV-BRH-004', 'Silver Geometric Brooch', 'Brooch', 'Elevate your style with our exquisite Silver Geometric Brooch, meticulously crafted from premium 999 Fine Silver that radiates timeless elegance and sophistication. This stunning piece features clean, contemporary geometric lines that seamlessly complement both traditional ethnic wear and modern outfits, making it the perfect accessory for weddings, festivals, and special occasions. Each brooch is a testament to exceptional craftsmanship, designed for the discerning Indian jewellery connoisseur who appreciates fine silver artistry and versatile, wearable luxury.', 31700.68, 19.91, '999 Fine Silver', '/images/products/silver-brooch-geometric-004.jpg', 0, 0, '2025-04-25', 4),
(91, 'SLV-BRC-005', 'Silver Bangle Style Bracelet', 'Bracelet', 'Elevate your elegance with our exquisite Silver Bangle Style Bracelet, meticulously crafted from 999 fine silver that radiates timeless beauty and authenticity. Perfect for both everyday wear and special occasions—from festive celebrations to intimate gatherings—this stunning bangle combines traditional Indian jewellery aesthetics with contemporary design. Each piece is a testament to superior craftsmanship, showcasing the lustrous purity and refined artistry that makes fine silver jewellery a cherished heirloom for generations to come.', 34796.86, 25.6, '999 Fine Silver', '/images/products/silver-bracelet-bangle-style-005.jpg', 0, 6, '2025-05-01', 3),
(92, 'SLV-NCK-005', 'Silver Pendant Chain Necklace', 'Necklace', 'Elevate your ethnic collection with our exquisite Silver Pendant Chain Necklace, meticulously crafted from premium 925 Sterling Silver that guarantees lasting brilliance and durability. This versatile pendant chain seamlessly complements both traditional ensembles and contemporary styles, making it the perfect choice for weddings, festivals, and everyday celebrations. Experience the timeless elegance and authentic craftsmanship that defines our commitment to delivering jewellery pieces worthy of your most cherished moments.', 17844.7, 54.32, '925 Sterling Silver', '/images/products/silver-necklace-pendant-chain-005.jpg', 1, 56, '2025-05-04', 9),
(93, 'SLV-HRP-002', 'Silver Clip Hair Pin', 'Hair Pin', 'Introducing our exquisite Silver Clip Hair Pin, meticulously crafted from 999 Fine Silver to add an elegant touch to your everyday look or special occasions. This beautifully designed clip-style hair pin combines traditional artisanal craftsmanship with contemporary aesthetics, perfect for adorning your hair at weddings, festivals, parties, and cultural celebrations. Elevate your personal style with this timeless piece of Indian silver jewellery that seamlessly blends sophistication with versatility.', 21188.39, 5.01, '999 Fine Silver', '/images/products/silver-hair-pin-clip-002.jpg', 1, 68, '2025-05-06', 8),
(94, 'SLV-PND-002', 'Silver Gemstone Pendant', 'Pendant', 'Experience the perfect blend of elegance and tradition with our exquisite Silver Gemstone Pendant, crafted from premium 925 Sterling Silver that promises enduring brilliance and purity. This masterfully designed piece features a radiant gemstone centerpiece that catches light beautifully, making it an ideal choice for weddings, festivals, daily wear, or special celebrations—seamlessly complementing both traditional and contemporary styles. Each pendant is meticulously handcrafted by skilled artisans, embodying the timeless sophistication that defines Indian jewellery heritage while offering versatile elegance for the modern woman.', 34278.63, 15.75, '925 Sterling Silver', '/images/products/silver-pendant-gemstone-002.jpg', 1, 67, '2025-05-07', 11),
(95, 'SLV-BNG-008', 'Silver Kada Bangle', 'Bangle', 'Elevate your traditional style with our exquisite Silver Kada Bangle, meticulously crafted from premium 999 Fine Silver that showcases authentic Indian artistry and elegance. This versatile bangle seamlessly transitions from everyday wear to special occasions, making it a perfect addition to both casual and festive outfits while complementing traditional ethnic attire beautifully. Each kada is expertly designed with precision and care, reflecting the timeless charm and cultural significance of traditional silver jewellery that every discerning jewelry connoisseur cherishes.', 1729.22, 30.71, '999 Fine Silver', '/images/products/silver-bangle-kada-008.jpg', 1, 35, '2025-05-20', 2),
(96, 'SLV-ANK-006', 'Silver Payal Anklet', 'Anklet', 'Introducing our exquisite Silver Payal Anklet, meticulously crafted from pure 999 fine silver that showcases the timeless elegance of traditional Indian jewellery design. This beautifully articulated payal is perfect for weddings, festivals, and special celebrations, adding an authentic touch of grace to your traditional attire while maintaining the lustrous brilliance that only fine silver can deliver. Each piece is expertly handcrafted to ensure premium quality and lasting beauty, making it an ideal choice for those who appreciate both cultural heritage and exceptional craftsmanship.', 9326.48, 28.15, '999 Fine Silver', '/images/products/silver-anklet-payal-006.jpg', 1, 28, '2025-05-31', 1),
(97, 'SLV-RNG-004', 'Silver Stackable Ring', 'Ring', 'Introducing our exquisite Silver Stackable Ring, meticulously crafted from 999 Fine Silver that promises timeless elegance and superior quality for the discerning buyer. This versatile piece features a contemporary stackable design, allowing you to mix and match to create your own unique combinations—perfect for everyday wear, festive celebrations, or special occasions. Each ring is a testament to our commitment to fine craftsmanship, blending traditional artistry with modern aesthetics to complement your personal style and add a touch of sophisticated sparkle to any occasion.', 9031.36, 12.46, '999 Fine Silver', '/images/products/silver-ring-stackable-004.jpg', 1, 9, '2025-06-10', 12),
(98, 'SLV-EAR-010', 'Silver Hoop Earring', 'Earring', 'Timeless elegance meets superior craftsmanship in these exquisite 925 Sterling Silver Hoop Earrings, meticulously designed to complement both traditional and contemporary styles. Perfect for every occasion—from festive celebrations to everyday sophistication—these lustrous silver hoops showcase the finest quality hallmarked sterling silver that ensures durability and lasting brilliance. Each piece reflects authentic Indian jewellery artistry, making it an essential addition to your collection that transcends seasons and trends.', 2781.48, 5.63, '925 Sterling Silver', '/images/products/silver-earring-hoop-010.jpg', 1, 11, '2025-06-10', 7),
(99, 'SLV-CHN-003', 'Silver Box Chain', 'Chain', 'Elevate your everyday style with our exquisitely crafted Silver Box Chain, meticulously designed from premium 925 Sterling Silver that promises durability and lustrous brilliance. This versatile piece features a sophisticated box link pattern that seamlessly transitions from casual daywear to special occasions, making it an essential addition to your jewellery collection. Perfect for layering or wearing solo, this authentic sterling silver chain embodies traditional Indian craftsmanship while offering the timeless elegance and purity that discerning jewellery enthusiasts truly value.', 12533.02, 10.96, '925 Sterling Silver', '/images/products/silver-chain-box-003.jpg', 1, 80, '2025-06-11', 5),
(100, 'SLV-CFL-004', 'Silver Monogram Cufflink', 'Cufflink', 'Elevate your formal wardrobe with these exquisite Silver Monogram Cufflinks, meticulously crafted from premium 925 Sterling Silver that epitomizes timeless elegance and sophistication. Perfect for weddings, business meetings, and special occasions, these personalized cufflinks showcase impeccable artisanal craftsmanship that reflects the rich heritage of Indian silver jewellery. The refined monogram detailing adds a distinctive personal touch, making these cufflinks an ideal investment piece that seamlessly complements both traditional and contemporary formal attire.', 12332.01, 9.6, '925 Sterling Silver', '/images/products/silver-cufflink-monogram-004.jpg', 0, 1, '2025-06-14', 6);


-- fabricate-flush


SET FOREIGN_KEY_CHECKS = 1;
